-- ==============================================================================
-- ChessKidoo Supabase Complete Schema
-- Copy and paste this entire script into your Supabase SQL Editor and run it.
-- This will create all the necessary tables for the frontend to work perfectly.
-- ==============================================================================

-- 1. USERS TABLE
-- Stores students, coaches, admins, and parents.
CREATE TABLE IF NOT EXISTS public.users (
    id TEXT PRIMARY KEY,
    userid TEXT,
    email TEXT,
    full_name TEXT,
    role TEXT,
    phone_number TEXT,
    city TEXT,
    level TEXT,
    rating INTEGER DEFAULT 800,
    coach TEXT,
    batch TEXT,
    session TEXT,
    schedule TEXT,
    fee TEXT,
    status TEXT,
    due_date TEXT,
    join_date TEXT,
    age INTEGER,
    grade TEXT,
    puzzle INTEGER DEFAULT 0,
    game INTEGER DEFAULT 0,
    star INTEGER DEFAULT 0,
    photo TEXT,
    certificate TEXT,
    last_note TEXT,
    childEmail TEXT, -- Used for parent accounts
    timetable TEXT, -- Used for coaches
    revenue TEXT,   -- Used for coaches
    classes INTEGER, -- Used for coaches
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. EXPENSES TABLE
-- Tracks academy expenditures.
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date TEXT,
    category TEXT,
    description TEXT,
    amount TEXT,
    mode TEXT,
    bill TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. DOCUMENT TABLE
-- Stores uploaded documents and class files.
CREATE TABLE IF NOT EXISTS public.document (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    file_name TEXT,
    name TEXT,
    level TEXT,
    coach TEXT,
    batch TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. ATTENDANCE TABLE
-- Tracks daily attendance for students.
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid TEXT,
    date TEXT,
    status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. RATINGS TABLE
-- Tracks ELO rating history over time for students.
CREATE TABLE IF NOT EXISTS public.ratings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id TEXT,
    online INTEGER,
    international INTEGER,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. TOUR RATINGS TABLE
-- Tracks tournament results and rating changes.
CREATE TABLE IF NOT EXISTS public.tourRatings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id TEXT,
    name TEXT,
    result TEXT,
    change TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. RESOURCES TABLE
-- Tracks homework, class notes, and puzzles.
CREATE TABLE IF NOT EXISTS public.resources (
    id TEXT PRIMARY KEY,
    name TEXT,
    batch TEXT,
    type TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. MEETINGS TABLE
-- Tracks scheduled online classes and Google Meet links.
CREATE TABLE IF NOT EXISTS public.meetings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date TEXT,
    coach TEXT,
    title TEXT,
    link TEXT,
    time TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. LEADS TABLE
-- Tracks "Book a Free Demo" form submissions.
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    phone TEXT,
    parent_name TEXT,
    child_age TEXT,
    city TEXT,
    status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. COACH NOTES TABLE
-- Stores feedback notes from coaches to students.
CREATE TABLE IF NOT EXISTS public.coach_notes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student TEXT,
    coach TEXT,
    text TEXT,
    date TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 11. CREDENTIALS TABLE
-- Stores custom passwords for the mock-auth system.
CREATE TABLE IF NOT EXISTS public.credentials (
    email TEXT PRIMARY KEY,
    password TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 12. BATCH LINKS TABLE
-- Stores Google Meet links for each batch level.
CREATE TABLE IF NOT EXISTS public.batch_links (
    batch_level TEXT PRIMARY KEY,
    link TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 13. CLASSES TABLE
-- Stores structured class schedules.
CREATE TABLE IF NOT EXISTS public.classes (
    id TEXT PRIMARY KEY,
    title TEXT,
    level TEXT,
    coach TEXT,
    schedule TEXT,
    students INTEGER DEFAULT 0,
    max_students INTEGER DEFAULT 10,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- SCHEMA ADDITIONS — Run these if you already have the tables created above.
-- These are safe to re-run (uses ADD COLUMN IF NOT EXISTS).
-- ==============================================================================

-- Streak tracking columns on users
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS streak_count INTEGER DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS streak_last_date TEXT;

-- Spaced Repetition System data (JSON string, per student)
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS srs_data TEXT;

-- ==============================================================================
-- SECURITY & ACCESS POLICIES
-- Since the frontend handles its own mock-auth and accesses Supabase directly,
-- we will disable Row Level Security (RLS) to ensure the API calls don't get blocked.
-- Alternatively, if you want security, you should use anon-key public policies.
-- ==============================================================================

-- Disable RLS on all tables so your frontend db.js can freely read/write
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.document DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ratings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tourRatings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.meetings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.credentials DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.batch_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes DISABLE ROW LEVEL SECURITY;

-- Grant public anon access to perform all operations
GRANT ALL ON TABLE public.users TO anon;
GRANT ALL ON TABLE public.expenses TO anon;
GRANT ALL ON TABLE public.document TO anon;
GRANT ALL ON TABLE public.attendance TO anon;
GRANT ALL ON TABLE public.ratings TO anon;
GRANT ALL ON TABLE public.tourRatings TO anon;
GRANT ALL ON TABLE public.resources TO anon;
GRANT ALL ON TABLE public.meetings TO anon;
GRANT ALL ON TABLE public.leads TO anon;
GRANT ALL ON TABLE public.coach_notes TO anon;
GRANT ALL ON TABLE public.credentials TO anon;
GRANT ALL ON TABLE public.batch_links TO anon;
GRANT ALL ON TABLE public.classes TO anon;

-- Grant usage on sequences if any (for BIGINT generated by default)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;

-- ==============================================================================
-- 10. STORAGE BUCKET: DOCUMENTS
-- The admin portal uploads student certificates to this bucket.
-- ==============================================================================

-- Create the 'documents' storage bucket and make it public
INSERT INTO storage.buckets (id, name, public) 
VALUES ('documents', 'documents', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Explicitly drop existing policies to avoid conflict errors when rerunning
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Allow Uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow Deletes" ON storage.objects;

-- Allow public read access to all files in the documents bucket
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'documents');

-- Allow anon/authenticated users to upload files
CREATE POLICY "Allow Uploads" 
ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'documents');

-- Allow anon/authenticated users to delete files
CREATE POLICY "Allow Deletes" 
ON storage.objects FOR DELETE 
USING (bucket_id = 'documents');
